'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let words=window.WORDS||[],map=new Map(words.map(w=>[w[0],w])),page='home',current=null,classroom=false,session=[],review=[],ri=0,revealed=false,toastTimer;
let state={history:[],saved:[],mastered:[]};try{let s=JSON.parse(localStorage.getItem('wordlab-v2'));for(const k of Object.keys(state))if(Array.isArray(s?.[k]))state[k]=s[k].filter(w=>map.has(w))}catch{}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',2600)}
function persist(){try{localStorage.setItem('wordlab-v2',JSON.stringify(state))}catch{toast('浏览器未允许保存，当前记录仅在本次打开期间保留')}sidebar()}
function row(w){return `<button class="row" data-word="${esc(w[0])}"><strong>${esc(w[0])}</strong><span>${esc(w[2].split('\n')[0])}</span></button>`}
function sidebar(){let list=classroom?session:state.history;$('#recent-title').textContent=classroom?'本节课 · '+list.length+' 词':'最近查询';$('#recent').innerHTML=list.length?list.slice(0,12).map(k=>map.get(k)).filter(Boolean).map(row).join(''):'<p class="empty">还没有查过单词。<br>第一次查询后会出现在这里。</p>';$('#save-class').hidden=!classroom||!session.length;$('#count').textContent=state.saved.length;$('#class-toggle').innerHTML=classroom?'<span>✓ 正在课堂模式</span><small>点击退出 · 本节课记录会保留</small>':'<span>⚡ 课堂模式</span><small>连续查词，自动留住本节课的单词 →</small>'}
function home(){page='home';current=null;$('#content').innerHTML='<section class="panel welcome"><span class="eyebrow">MAKE IT YOURS</span><h2>遇到不认识的词？<br>从这里开始。</h2><p class="muted">输入完整单词查询，也可以输入开头字母或中文找词。</p><div class="chips">'+['exacerbate','compelling','underlying'].map(w=>`<button data-word="${w}">${w} ↗</button>`).join('')+'</div></section>';nav()}
function nav(){document.querySelectorAll('[data-page]').forEach(b=>{b.removeAttribute('aria-current');if(b.dataset.page===page)b.setAttribute('aria-current','page')})}
function detail(w,record=true){current=w;page='home';$('#suggestions').innerHTML='';$('#query').value=w[0];if(record){state.history=[w[0],...state.history.filter(x=>x!==w[0])].slice(0,100);if(classroom)session=[w[0],...session.filter(x=>x!==w[0])];persist()}const labels={cet4:'CET-4',cet6:'CET-6',ky:'考研',ielts:'IELTS',toefl:'TOEFL',gre:'GRE',gk:'高考',zk:'中考'};$('#content').innerHTML=`<article id="detail" class="panel"><div class="section-head"><span class="eyebrow">WORD EXPLORER</span><button data-action="home" class="text-button">返回首页</button></div><h2 class="word">${esc(w[0])}</h2><span class="phonetic">${w[1]?'/'+esc(w[1])+'/':'暂无音标'}</span><div class="actions"><button data-action="speak">◖ 发音</button><button class="primary" data-action="save">${state.saved.includes(w[0])?'★ 已收藏 · 取消':'☆ 加入生词本'}</button></div><div class="tags">${w[4].split(' ').filter(x=>labels[x]).map(x=>`<span class="badge">${labels[x]}</span>`).join('')}</div><p class="meaning">${esc(w[2])}</p>${w[3]?'<h3>英文释义</h3><p class="definition">'+esc(w[3])+'</p>':''}<p class="muted">词条来源：ECDICT。考试标签沿用原词库，非实时考试大纲。</p></article>`;$('#status').textContent='已找到 '+w[0]+(classroom?' · 继续输入下一个词即可':'');nav()}
function matches(q){q=q.trim().toLowerCase();if(!q)return[];let exact=map.get(q),out=exact?[exact]:[];for(const w of words){if(w!==exact&&(w[0].startsWith(q)||(/[\u3400-\u9fff]/.test(q)&&w[2].includes(q)))){out.push(w);if(out.length===8)break}}return out}
function search(){const q=$('#query').value.trim().toLowerCase();if(!q){$('#status').textContent='请输入单词或中文释义';$('#query').focus();return}let w=map.get(q);if(!w){w=words.find(w=>w[5]?.split('/').some(e=>e.split(':')[1]===q))}if(w){detail(w);return}let list=matches(q);$('#suggestions').innerHTML='';current=null;$('#content').innerHTML='<section class="panel"><h2>'+(list.length?'选择你想查询的词':'暂未找到 “'+esc(q)+'”')+'</h2>'+(list.length?list.map(row).join(''):'<p class="muted">请检查拼写，或输入前几个字母查看联想。当前为本地精选词库，未收录所有专有名词和短语。</p><a class="outline" href="https://www.youdao.com/result?word='+encodeURIComponent(q)+'&lang=en" target="_blank" rel="noreferrer">去有道查询 ↗</a>')+'</section>';$('#status').textContent=list.length?'找到 '+list.length+' 个候选词':'未找到该词；不会加入查询历史'}
function saved(){page='saved';current=null;let list=state.saved.map(w=>map.get(w));$('#content').innerHTML='<section class="panel"><div class="section-head"><h2>我的生词本 · '+list.length+'</h2><button data-action="review" class="primary">开始复习</button></div><p class="muted">已标记掌握 '+state.mastered.filter(w=>state.saved.includes(w)).length+' 词</p>'+(list.length?list.map(row).join(''):'<p class="empty">生词本还是空的。查到单词后，点击“加入生词本”。</p>')+'</section>';nav()}
function library(tag='cet6'){page='library';current=null;let list=words.filter(w=>w[4].split(' ').includes(tag));$('#content').innerHTML='<section class="panel"><h2>考试词库</h2><div class="chips">'+[['cet6','六级'],['cet4','四级'],['ky','考研'],['ielts','雅思']].map(([k,n])=>`<button data-tag="${k}" ${tag===k?'class="primary"':''}>${n}</button>`).join('')+'</div><p class="muted">当前分类 '+list.length+' 词 · 先展示前 80 词，可用顶部搜索查询全库。</p>'+list.slice(0,80).map(row).join('')+'</section>';nav()}
function showReview(){if(ri>=review.length){$('#content').innerHTML='<section class="panel"><h2>本轮复习完成 ✓</h2><p>你复习了 '+review.length+' 个单词。</p><button data-page="saved">回到生词本</button></section>';return}const w=map.get(review[ri]);$('#content').innerHTML='<section class="panel"><p class="muted">复习 '+(ri+1)+' / '+review.length+'</p><div class="review-word"><h2>'+esc(w[0])+'</h2><p class="meaning">'+(revealed?esc(w[2]):'回想一下它的意思')+'</p></div>'+(revealed?'<div class="actions"><button data-grade="again">还要再记</button><button class="primary" data-grade="known">已掌握</button></div>':'<button data-action="reveal" class="primary">查看释义</button>')+'</section>'}
$('#search-form').addEventListener('submit',e=>{e.preventDefault();search()});$('#query').addEventListener('input',()=>{const q=$('#query').value;$('#suggestions').innerHTML=matches(q).map(row).join('');$('#status').textContent=q.trim()?'点击候选词或按回车查询':'已加载 '+words.length.toLocaleString()+' 个词条'});$('#query').addEventListener('keydown',e=>{if(e.key==='Escape'){$('#suggestions').innerHTML=''}if(e.key==='ArrowDown'){e.preventDefault();$('#suggestions button')?.focus()}});$('#clear-query').onclick=()=>{$('#query').value='';$('#suggestions').innerHTML='';$('#query').focus()};$('#clear-history').onclick=()=>{if(classroom)session=[];else state.history=[];persist();toast(classroom?'本节课记录已清空':'查询历史已清空')};$('#class-toggle').onclick=()=>{classroom=!classroom;document.body.classList.toggle('classroom',classroom);sidebar();$('#query').value='';$('#query').focus()};$('#save-class').onclick=()=>{state.saved=[...new Set([...state.saved,...session])];persist();toast('已收藏本节课的 '+session.length+' 个单词');if(current)detail(current,false)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.word){detail(map.get(b.dataset.word));return}if(b.dataset.page){$('#suggestions').innerHTML='';({home,saved,library}[b.dataset.page])();return}if(b.dataset.tag){library(b.dataset.tag);return}switch(b.dataset.action){case'home':home();break;case'save':if(!current)return;const k=current[0];state.saved=state.saved.includes(k)?state.saved.filter(w=>w!==k):[k,...state.saved];persist();detail(current,false);toast(state.saved.includes(k)?'已加入生词本':'已取消收藏');break;case'speak':if(!current)return;if(!('speechSynthesis'in window)){toast('此浏览器不支持朗读');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(current[0]);u.lang='en-US';u.rate=.85;u.onerror=()=>toast('朗读失败，请检查设备语音服务');speechSynthesis.speak(u);break;case'review':if(!state.saved.length){toast('请先收藏单词');return}review=[...state.saved];ri=0;revealed=false;showReview();break;case'reveal':revealed=true;showReview();break}if(b.dataset.grade){let k=review[ri];state.mastered=state.mastered.filter(w=>w!==k);if(b.dataset.grade==='known')state.mastered.push(k);persist();ri++;revealed=false;showReview()}});
document.addEventListener('click',e=>{if(!e.target.closest('.search-area'))$('#suggestions').innerHTML=''});home();sidebar();$('#status').textContent=words.length?'已加载 '+words.length.toLocaleString()+' 个词条 · 支持英文、中文和词形查询':'词库加载失败，请刷新页面重试';
